#! /bin/bash
case "${1:-ip}" in
	ip)
		curl -sA "ipsb-wrapper/1.0" https://api.ip.sb/jsonip | jq
	;;
	whereami)
		curl -sA "ipsb-wrapper/1.0" https://api.ip.sb/geoip | jq
	;;
	help|*)
		echo 'usage: '
		echo '   ipsb ip/whereami/help'
	;;
esac
